services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: edulearn
      MYSQL_DATABASE: edulearn
    ports:
      - "3316:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: ./app
    container_name: astro
    ports:
      - "3000:4321"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && HOST=0.0.0.0 npm run dev"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://api/api # Dodaj zmienną środowiskową
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
