
# FROM node:22-alpine


# WORKDIR /usr/src/app

# COPY package*.json ./

# RUN npm install --omit=optional

# COPY . .

# EXPOSE 3000


# CMD ["npm", "run", "dev"]
FROM node:20-slim AS runtime
WORKDIR /app

COPY . .

RUN npm install
#RUN npm install --omit=optional
ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
#CMD node ./dist/server/entry.mjs
