CREATE DATABASE IF NOT EXISTS edulearn;

USE edulearn;

DROP TABLE IF EXISTS course_topics;
DROP TABLE IF EXISTS course_users;
DROP TABLE IF EXISTS course_images;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS topics;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'teacher', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS topics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    short_description VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255),
    related INT,
    user_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (related) REFERENCES courses(id)
);

CREATE TABLE IF NOT EXISTS course_topics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT,
    topic_id INT,
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (topic_id) REFERENCES topics(id)
);

CREATE TABLE IF NOT EXISTS course_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT,
    user_id INT,
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS course_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    course_id INT,
    image VARCHAR(255),
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON DELETE CASCADE
);

INSERT INTO users (username, email, password, role) VALUES
('admin', 'admin@example.com', 'admin123', 'admin'),
('teacher', 'teacher@example.com', 'teacher123', 'teacher'),
('user', 'user@example.com', 'user123', 'user'),
('johndoe', 'johndoe@example.com', 'password123', 'user'),
('janedoe', 'janedoe@example.com', 'password456', 'user'),
('bobsmith', 'bobsmith@example.com', 'password789', 'user'),
('sarahjones', 'sarahjones@example.com', 'password101112', 'teacher'),
('mikebrown', 'mikebrown@example.com', 'password131415', 'user'),
('emilywhite', 'emilywhite@example.com', 'password161718', 'user'),
('davidlee', 'davidlee@example.com', 'password192021', 'teacher'),
('laurasmith', 'laurasmith@example.com', 'password222324', 'user'),
('jameswilson', 'jameswilson@example.com', 'password252627', 'user'),
('jenniferbrown', 'jenniferbrown@example.com', 'password282930', 'user'),
('robertmiller', 'robertmiller@example.com', 'password313233', 'user'),
('karenjohnson', 'karenjohnson@example.com', 'password343536', 'user'),
('matthewwilson', 'matthewwilson@example.com', 'password373839', 'teacher'),
('lindajones', 'lindajones@example.com', 'password404142', 'user');


INSERT INTO topics (name) VALUES
('New'),
('Related'),
('Popular'),
('Trending'),
('Featured'),
('Free'),
('Reacr'),
('JavaScript'),
('Python'),
('C++'),
('C#'),
('C'),
('PHP'),
('Ruby'),
('Swift'),
('Kotlin'),
('Go'),
('Rust'),
('TypeScript'),
('Scala'),
('Perl'),
('Haskell'),
('Lua'),
('R'),
('Dart'),
('Elixir'),
('Clojure'),
('F#'),
('Erlang'),
('Rust'),
('Racket'),
('Scheme'),
('Lisp'),
('Prolog'),
('SQL'),
('NoSQL'),
('MongoDB'),
('MySQL'),
('PostgreSQL'),
('SQLite'),
('Oracle'),
('SQL Server'),
('MariaDB'),
('Cassandra'),
('Redis'),
('Firebase'),
('Sale');



-- First insert courses without related references
INSERT INTO `courses` (`title`, `short_description`, `description`, `price`, `image`, `related`, `user_id`, `created_at`) VALUES
('Web Development for Beginners', 'Learn the basics of web development', '<h2>What you will learn:</h2><ul><li>HTML Basics</li><li>CSS Styling</li><li>JavaScript Fundamentals</li></ul><p>This course is perfect for beginners looking to start their journey in web development.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 49.99, '/uploads/courses/course1.png', NULL, 1, NOW()),
('Advanced JavaScript Techniques', 'Master advanced JavaScript concepts', '<h2>Course Overview:</h2><p>Take your JavaScript skills to the next level with advanced topics like:</p><ul><li>ES6 and beyond</li><li>Asynchronous programming</li><li>Performance optimization</li></ul><p>Recommended for developers with prior JavaScript knowledge.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 99.99, '/uploads/courses/course2.png', NULL, 2, NOW()),
('Python for Data Science', 'Analyze and visualize data using Python', '<h2>Topics Covered:</h2><ul><li>Data manipulation with <strong>Pandas</strong></li><li>Data visualization with <strong>Matplotlib</strong> and <strong>Seaborn</strong></li><li>Basic Machine Learning techniques</li></ul><p>Start your data science journey today!</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 79.99, '/uploads/courses/course3.png', 1, 2, NOW()),
('Complete Guide to ReactJS', 'Build modern web applications with React', '<h2>Course Highlights:</h2><ul><li>React basics and components</li><li>State management with Redux</li><li>Using hooks and context API</li></ul><p>By the end of this course, you will have built a complete React application.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 119.99, '/uploads/courses/course4.png', NULL, 3, NOW()),
('Mastering SQL', 'Become proficient in database management', '<h2>What you will learn:</h2><p>In this course, you will gain a solid foundation in SQL, including:</p><ul><li>Writing complex queries</li><li>Database design principles</li><li>Optimizing database performance</li></ul><p>Suitable for both beginners and experienced developers.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 59.99, '/uploads/courses/course5.png', 2, 2, NOW()),
('UI/UX Design Essentials', 'Learn the fundamentals of user interface and experience design', '<h2>Course Description:</h2><p>Gain a deep understanding of user-centered design principles:</p><ul><li>Wireframing and prototyping</li><li>Designing with Figma</li><li>Usability testing</li></ul><p>Transform your creative ideas into visually appealing designs.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 89.99, '/uploads/courses/course6.png', 3, 7, NOW()),
('DevOps Fundamentals', 'Learn DevOps principles and practices', '<h2>Topics:</h2><p>This course covers:</p><ul><li>Continuous integration and delivery</li><li>Infrastructure as code</li><li>Monitoring and logging</li></ul><p>Ideal for developers and system administrators.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 149.99, '/uploads/courses/course7.png', NULL, 7, NOW()),
('Cloud Computing Basics', 'Understand the essentials of cloud technology', '<h2>Highlights:</h2><p>This beginner-friendly course includes:</p><ul><li>Introduction to cloud platforms</li><li>Working with AWS, Azure, and Google Cloud</li><li>Deploying cloud applications</li></ul><p>Get started with cloud computing today!</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 69.99, '/uploads/courses/course11.png', 4, 7, NOW());

-- Then insert courses with related references
INSERT INTO `courses` (`title`, `short_description`, `description`, `price`, `image`, `related`, `user_id`, `created_at`) VALUES
('Mobile App Development with Flutter', 'Create cross-platform mobile apps', '<h2>Key Features:</h2><ul><li>Understanding Flutter basics</li><li>Building responsive UIs</li><li>Integrating APIs</li></ul><p>This course is perfect for those looking to develop mobile apps for both Android and iOS.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 129.99, '/uploads/courses/course9.png', NULL, 7, NOW()),
('Cybersecurity Essentials', 'Protect systems from cyber threats', '<h2>Learn:</h2><ul><li>Network security principles</li><li>Data encryption methods</li><li>Identifying and preventing cyber attacks</li></ul><p>Stay ahead in the evolving field of cybersecurity.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 99.99, '/uploads/courses/course10.png', 1, 7, NOW()),
('Machine Learning A-Z', 'Master machine learning from scratch', '<h2>Topics Covered:</h2><ul><li>Supervised and unsupervised learning</li><li>Working with TensorFlow and Scikit-learn</li><li>Building prediction models</li></ul><p>Build intelligent systems and boost your career!</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 149.99, '/uploads/courses/course11.png', 3, 2, NOW()),
('Photography for Beginners', 'Learn the art of photography', '<h2>Course Highlights:</h2><p>Discover photography techniques such as:</p><ul><li>Camera settings and composition</li><li>Lighting and exposure</li><li>Editing photos with Lightroom</li></ul><p>Unleash your creative potential with this beginner-friendly course.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 59.99, '/uploads/courses/course12.png', NULL, 7, NOW()),
('Digital Marketing Mastery', 'Become an expert in digital marketing', '<h2>What You Will Learn:</h2><p>Master the following areas:</p><ul><li>SEO strategies</li><li>Social media marketing</li><li>Email campaigns and analytics</li></ul><p>Boost your business or start a marketing career.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 89.99, '/uploads/courses/ccourse8.png', NULL, 2, NOW()),
('Game Development with Unity', 'Create immersive games using Unity', '<h2>Topics Covered:</h2><ul><li>Game mechanics and physics</li><li>Building 2D and 3D environments</li><li>Deploying games on various platforms</li></ul><p>Perfect for aspiring game developers.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 119.99, '/uploads/courses/course6.png', NULL, 7, NOW()),
('Ethical Hacking Basics', 'Learn ethical hacking techniques', '<h2>Key Topics:</h2><ul><li>Penetration testing</li><li>Vulnerability assessment</li><li>Using Kali Linux tools</li></ul><p>Learn to think like a hacker and protect systems effectively.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 139.99, '/uploads/courses/course4.png', 2, 2, NOW()),
('Data Analysis with Excel', 'Become a pro at data analysis', '<h2>Highlights:</h2><p>Learn how to:</p><ul><li>Use advanced Excel functions</li><li>Analyze datasets with pivot tables</li><li>Create interactive dashboards</li></ul><p>Improve your analytical skills with this practical course.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 49.99, '/uploads/courses/course2.png', 5, 7, NOW()),
('AI for Beginners', 'Understand the basics of Artificial Intelligence', '<h2>What you will learn:</h2><p>This course introduces:</p><ul><li>History and concepts of AI</li><li>Applications in real-world scenarios</li><li>AI ethics and future trends</li></ul><p>Start your AI journey today!</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 79.99, '/uploads/courses/course8.png', 7, 2, NOW()),
('Blockchain Technology Explained', 'Explore the fundamentals of blockchain', '<h2>Course Details:</h2><p>Topics include:</p><ul><li>How blockchain works</li><li>Cryptocurrencies like Bitcoin</li><li>Smart contracts and DApps</li></ul><p>Join the revolution with this beginner-friendly course.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 109.99, '/uploads/courses/course9.png', 8, 7, NOW()),
('Public Speaking Skills', 'Master the art of public speaking', '<h2>What You Will Gain:</h2><ul><li>Overcome stage fright</li><li>Deliver impactful presentations</li><li>Engage and inspire your audience</li></ul><p>Enhance your communication skills with this course.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 39.99, '/uploads/courses/course2.png', NULL, 2, NOW()),
('Fitness and Nutrition Fundamentals', 'Achieve your fitness goals', '<h2>Course Highlights:</h2><p>Learn about:</p><ul><li>Creating a balanced diet plan</li><li>Effective workout routines</li><li>Tracking progress for long-term success</li></ul><p>Get fit and healthy with expert guidance.</p><h2>Introduction</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<strong>Proin a risus sit amet nulla</strong> vehicula ultrices a ac massa. Sed vitae ex et odio venenatis vulputate id eget lorem. Integer nec libero ac ligula tincidunt consequat.<em>Donec nec nisi nec lacus sollicitudin vulputate.</em>Aenean dignissim orci vel lacus feugiat posuere. Mauris tincidunt libero nec eros consequat, a tempus nunc gravida. Nullam efficitur nisi nec nisl pharetra, ut laoreet eros vehicula.</p><h3>Course Scope</h3><ul><li><strong>Module 1:</strong> Basics and introductory theory</li><li><strong>Module 2:</strong> Advanced techniques and analytical tools</li><li><strong>Module 3:</strong> Practical exercises in real-world projects</li><li><strong>Module 4:</strong> Tips and best practices from experts</li></ul><h3>Why is this important?</h3><p>The modern world demands an understanding of advanced topics.<strong>The knowledge you gain</strong> will assist you in everyday tasks and large-scale projects. This course is based on real-world examples that are easy to apply in practice.</p><p>Here are some questions youll find answers to:</p><ol><li>How to get started with modern tools</li><li>What techniques lead to the best results</li><li>How to avoid common mistakes and pitfalls in this field</li></ol><h3>Real-Life Examples</h3><p>Our course includes numerous<strong>case studies</strong> and practical tasks to help you grasp key concepts. For instance:</p><blockquote>In one of my projects, I quickly learned how to automate company processes. Thanks to this knowledge, I saved over 30% of my teams work time. – John, participant</blockquote><p>In another module, we discuss how to implement new tools efficiently and in line with best practices. The course allows you to practice various scenarios and build confidence in challenging situations.</p><h3>Course Content</h3><p>Here are some of the topics covered in depth:</p><ul><li>Introduction to data analysis and supporting tools</li><li>Creating reports, visualizations, and interpreting results</li><li>Advanced optimization techniques</li><li>Data security and protection</li></ul><h3>Summary</h3><p>During the course, you will gain comprehensive knowledge that will allow you to develop your skills and achieve higher professional goals.<em>We provide practical tips</em> and access to materials that will support your growth long after the course is over.</p>', 29.99, '/uploads/courses/course6.png', NULL, 7, NOW());

INSERT INTO course_topics (course_id, topic_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 4),
(2, 1),
(2, 5),
(2, 6),
(3, 7),
(3, 1),
(3, 8),
(3, 9),
(4, 10),
(4, 1),
(5, 11),
(5, 1),
(6, 12),
(6, 1),
(7, 13),
(7, 1),
(8, 14),
(8, 1),
(9, 1),
(9, 5),
(10, 5);
